### ISSUE TITLE
Running the code to build the graphs in the population density article

### ISSUE THREAD

**Issue by greggman** [mountainMath/doodles#2]
I loved this article

https://doodles.mountainmath.ca/blog/2019/04/24/population-weighted-densities/

Could you provide a few even terse pointers on how to go about running the code to generate those graphs? I won't ask for a ton of help but even where to start. I guess I need to download `r`? But is there more to it? Looks like I need to install blogdown? Is that probably it? Just trying to avoid hours of some simple basics. Guess I should just try but thought I'd ask.

**Comment by mountainMath** [comment]
All you need to do is install R. For easier use I recommend also downloading RStudio and running it from within RStudio. There are some required packages, it will trigger error messages when running it without the packages, you will just have to install the required packages it needs in R. The first time you run it it will download several gigabytes of population data, that might take a while.

**Comment by greggman** [comment]
Ok Thanks!

I install R, installed R Studio, Installed Blogsite, Opened the project in R. Installed lots of packages. It failed on some post. So I deleted all the blog posts except the one I was hoping to build and got this error

```
==> rmarkdown::render_site(encoding = 'UTF-8')

Rendering content/posts/2019-04-24-population-weighted-densities.Rmarkdown
Joining, by = "name"
trying URL 'http://cidportal.jrc.ec.europa.eu/ftp/jrc-opendata/GHSL/GHS_POP_GPW4_GLOBE_R2015A/GHS_POP_GPW42015_GLOBE_R2015A_54009_250/V1-0/GHS_POP_GPW42015_GLOBE_R2015A_54009_250_v1_0.zip'
Content type 'application/zip' length 1079931996 bytes (1029.9 MB)
==================================================
downloaded 1029.9 MB

Quitting from lines 49-100 (2019-04-24-population-weighted-densities.Rmarkdown) 
Error in if (!dir.exists(exdir)) dir.create(exdir) : 
  argument is of length zero
Calls: local ... lapply -> FUN -> pop_weighted_density_for -> get_GHS_for
Execution halted
Error in render_page(f) : 
  Failed to render 'content/posts/2019-04-24-population-weighted-densities.Rmarkdown'
Calls: <Anonymous> ... <Anonymous> -> build_site -> build_rmds -> render_page
Execution halted

Exited with status 1.
```

Been googling but this is my first experience with R so so far no luck finding what I need to fix

**Comment by mountainMath** [comment]
Ah, I think that should get fixed by adding `options(custom_data_path="<directory for custom data download>")` at the top of the script. I have this set in my environment variable.

**Comment by greggman** [comment]
Okay well, that got further. Then it failed because 'zip' wasn't installed. So installed 'zip' and it needed to download 1gig again but got this error

```
==> rmarkdown::render_site(encoding = 'UTF-8')

Rendering content/posts/2019-04-24-population-weighted-densities.Rmarkdown
Joining, by = "name"
trying URL 'http://cidportal.jrc.ec.europa.eu/ftp/jrc-opendata/GHSL/GHS_POP_GPW4_GLOBE_R2015A/GHS_POP_GPW42015_GLOBE_R2015A_54009_250/V1-0/GHS_POP_GPW42015_GLOBE_R2015A_54009_250_v1_0.zip'
Content type 'application/zip' length 1079931996 bytes (1029.9 MB)
==================================================
downloaded 1029.9 MB

Quitting from lines 49-100 (2019-04-24-population-weighted-densities.Rmarkdown) 
Error in get_GHS_for(NULL, type = type, year = year) : 
  Downloading of raster file failed, probably needs some tweaking of the code.
Calls: local ... lapply -> FUN -> pop_weighted_density_for -> get_GHS_for
Execution halted
Error in render_page(f) : 
  Failed to render 'content/posts/2019-04-24-population-weighted-densities.Rmarkdown'
Calls: <Anonymous> ... <Anonymous> -> build_site -> build_rmds -> render_page
Execution halted

Exited with status 1.
```

I guess I need to learn R so I can debug.

Thanks for the help.

**Comment by mountainMath** [comment]
Sorry, looks like my code is not as "reproducible" as I thought it was. Happy to help out track this down.
